languageCode = "en-gb"
title = "Joe Green"
baseurl = "http://joeg.uk/"

enableRobotsTXT = true
googleAnalytics = "UA-89413599-1"

PygmentsCodeFences = true
PygmentsUseClasses = true

[permalinks]
  post = "/:year/:month/:title/"

[params]
    disqusShortname = "joeg-uk"
    description = "Software Engineering, DevOps & Architecture"
    copyright = " "

[taxonomies]
    tag = "tags"
    series = "series"

[[menu.main]]
    name = "GitHub"
    pre = "<i class='fa fa-github'></i>"
    target = "_blank"
    identifier = "github"
    url = "https://github.com/mrjgreen"
    weight = 100

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"